---
- name: Allow firewall for Control-plane node(s)
  block:
    - name: CentOS Control-plane node(s) firewall rules
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 6443/tcp
        - 2379-2380/tcp
        - 10250/tcp
        - 10251/tcp
        - 10252/tcp
      when: ansible_distribution | lower == "centos"

    - name: Ubuntu Control-plane node(s) firewall rules
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 6443
        - 2379:2380
        - 10250
        - 10251
        - 10252
      when: ansible_distribution | lower == "ubuntu"
  when: inventory_hostname in groups['master']

- name: Allow firewall for Worker node(s)
  block:
    - name: CentOS Worker node(s) firewall rules
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 10250/tcp
        - 30000-32767/tcp
      when: ansible_distribution | lower == "centos"

    - name: Ubuntu Worker node(s) firewall rules
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 10250
        - 30000:32767
      when: ansible_distribution | lower == "ubuntu"
  when: inventory_hostname in groups['node']
